### PR TITLE
Suport for benchmarking times  of OBDA phases

### PR DESCRIPTION
**Pull request by ArenasGuerreroJulian**
Benchmarking times for the different OBDA phases is included. Path of the benchmark results is indicated in the properties file via benchmark.file.path. Benchmark output is a json file.

### CODE REVIEW

**Comment by dachafra** [comment]
@ArenasGuerreroJulian what arr you exactly measuring in the rewriting phase? morph-rdb does not include that phase, so I assume that is not necessary to give that output

**Comment by ArenasGuerreroJulian** [comment]
At this moment rewriting phase is not been measured as Morph does not included (output time is always 0 seconds). However, I included it to have the consider the same phases specified in NPD benchmark

**Comment by dachafra** [comment]
as it's not performed in the pipeline, I would recommend to not show that measurement in the output file. Rest is ok for me

**Review by dachafra — APPROVED** [review]

**Comment by dachafra** [comment]
@ArenasGuerreroJulian could you also create a new folder under morph-examples with a simple example of the configuration? in order to know how to test it. Thanks!

**Review by fpriyatna — COMMENTED** [review]
looks good to me

**Comment by dachafra** [comment]
merging the PR...

**Pull request merged**
